language: R
sudo: false
cache: packages
deploy:
  provider: releases
  api_key:
    secure: cLWksstw4eYXi7Fv2hxvnbqIqUhCGQNfWYeUFxNc2EUBdGzhZOpwGBpEQAV0vPLMHDPqqxy354BJ8wMKKqb9oA2/XMN5/qcRNv6ISDwgKTPPI6KPcUw/PKCJpHHcFPCvDm4Qc01wXEx2kSEbPp99BaWM7cXel3v66lip5hcA//uRINbFN/dlmIVMBWRAkHi01lJIP5eCMt15PRt/c7J/tuJmR5IWzxtdRfbBJaEgq8vlQix6UYe/u8wi2lv+I/eHBkIMa/AhK2b0op70GNE/DNFXkWIi7hmoxU7ZcWLgr7KbxvJ2x4gJ0aTictOT/WRoEgHciiImhqpsvFvp1KdeTw8HJoHpP3tCHAEDFQ9UYC/P06HFy+R/B4X3e5cvvBi8HrHnAX28a0Zs6psRuzZ4kygAYvqarlS+lb6mCnrYf/8Sw9jChaBdLLlWn6W+RymKeh/O3JyhORT13DCMTcqn23LnoKKV4KL6qafR7XCNkG22tWLv0hk4jCoCUm7lkXsHtZtVPK1W7Jsa0QPdNFiQkV/p87vMNQ8Gyc3dCBWFENwZr3GiB2QUablanAgJpuVXdS49ZBXaOKcjopF9mawExvbkTqqh7IRFL2ft2OFrmESU3zOEIHKgvPVxYKYfbvEcR2RpwxkSN9ApIkAV2RGjw6dUWasZM3XQt5rA/cL2yt0=
  file: StigTest_1.0.3.0000.tar.gz
  on:
    repo: Stiggedy/StigTest
