# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
deploy:
  provider: releases
  file: "StigTest_1.0.0.0000.tar.gz"
  skip_cleanup: true
  on:
    tags: true
